{{- $connectionString := printf "Host=%s-postgres;Port=%v;Database=%s;Username=%s;Password=%s" (include "notes-stack.fullname" .) .Values.postgres.service.port .Values.postgres.database .Values.postgres.username .Values.postgres.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notes-stack.fullname" . }}-postgres
  labels:
    {{- include "notes-stack.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.postgres.password | quote }}
  connectionString: {{ $connectionString | quote }}
