apiVersion: v1
kind: Service
metadata:
  name: {{ include "notes-stack.fullname" . }}-api
  labels:
    {{- include "notes-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    {{- include "notes-stack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
