apiVersion: v1
kind: Service
metadata:
  name: {{ include "notes-stack.fullname" . }}-postgres
  labels:
    {{- include "notes-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  selector:
    {{- include "notes-stack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: postgres
